export const persian: Record<string, string> = {
  'Names resolve through the game tunnel and never fall back to local DNS. Shared Windows lookups use the game; identifiable VPN apps can use their own VPN resolver.':
    'نام‌ها از طریق تونل بازی پیدا می‌شوند و هرگز به DNS محلی برنمی‌گردند. درخواست‌های مشترک ویندوز از بازی استفاده می‌کنند؛ برنامه‌های قابل‌شناسایی VPN می‌توانند از DNS همان VPN استفاده کنند.',
  'Names assigned to the VPN resolve through its node and never fall back to local DNS. While a game runs, shared Windows lookups use the game resolver.':
    'نام‌های مربوط به VPN از طریق گره آن پیدا می‌شوند و هرگز به DNS محلی برنمی‌گردند. هنگام اجرای بازی، درخواست‌های مشترک ویندوز از DNS بازی استفاده می‌کنند.',
  'While the node is not answering, selected apps are blocked. Remote DNS always stays on its tunnel, even when this switch is off.':
    'وقتی گره پاسخ نمی‌دهد، برنامه‌های انتخاب‌شده مسدود می‌شوند. DNS راه دور همیشه در تونل خود می‌ماند، حتی وقتی این کلید خاموش باشد.',
  'Selected traffic can use your normal connection when the node is unavailable. Remote DNS still stays on its tunnel.':
    'وقتی گره در دسترس نیست، ترافیک انتخاب‌شده می‌تواند از اتصال عادی استفاده کند. DNS راه دور همچنان در تونل خود می‌ماند.',
  'Statistics for': 'آمار برای',
  Game: 'بازی',
  'Carried by the VPN': 'منتقل‌شده از طریق VPN',
  "In engine-managed modes, totals count selected IPv4 packets once. Node totals include tunnel overhead and extra relay copies, so they can exceed the overall total. Direct L2TP totals use Windows RAS connection counters. Split-tunnel flows without a process name appear as Unattributed. All-traffic and direct L2TP sessions do not provide per-application usage. Devices are the LAN proxy's clients, by address; their traffic is also part of the overall total. VPN traffic is counted separately, under VPN.":
    'در حالت‌هایی که موتور مدیریت می‌کند، مجموع‌ها هر بسته IPv4 انتخاب‌شده را یک بار می‌شمارند. مجموع گره‌ها شامل سربار تونل و نسخه‌های اضافی رله است و ممکن است از مجموع کل بیشتر شود. مجموع L2TP مستقیم از شمارنده‌های اتصال RAS ویندوز است. جریان‌های تونل تفکیکی بدون نام فرایند به‌صورت نامشخص نمایش داده می‌شوند. اتصال‌های همه ترافیک و L2TP مستقیم مصرف هر برنامه را ارائه نمی‌دهند. دستگاه‌ها کاربران پراکسی شبکه محلی بر اساس نشانی هستند و ترافیک آن‌ها نیز بخشی از مجموع کل است. ترافیک VPN جداگانه و در بخش VPN شمرده می‌شود.',
  "VPN traffic is counted separately from the game's and never added to it. Traffic the game session selects is the game's, even when the VPN lists the same app. The node total includes the VPN's tunnel overhead. An L2TP VPN, or a VPN in all-traffic mode, does not provide per-application usage.":
    'ترافیک VPN جدا از ترافیک بازی شمرده می‌شود و هرگز به آن اضافه نمی‌شود. ترافیکی که اتصال بازی انتخاب می‌کند متعلق به بازی است، حتی اگر VPN همان برنامه را فهرست کرده باشد. مجموع گره شامل سربار تونل VPN است. VPN با L2TP یا VPN در حالت همه ترافیک مصرف هر برنامه را ارائه نمی‌دهد.',
  'Test proxy': 'آزمایش پراکسی',
  'The proxy works': 'پراکسی کار می‌کند',
  VPN: 'VPN',
  'A second connection for everyday apps, beside your game and never in its way.':
    'اتصالی دوم برای برنامه‌های روزمره، کنار بازی شما و بدون مزاحمت برای آن.',
  'VPN is off': 'VPN خاموش است',
  'Connecting…': 'در حال اتصال…',
  Connecting: 'در حال اتصال',
  'Reconnecting…': 'در حال اتصال دوباره…',
  Reconnecting: 'اتصال دوباره',
  'VPN is on': 'VPN روشن است',
  'Node not answering': 'گره پاسخ نمی‌دهد',
  Degraded: 'ناپایدار',
  'Paused for your game': 'به خاطر بازی شما متوقف شد',
  'VPN could not connect': 'VPN متصل نشد',
  'Import a .conf file': 'وارد کردن فایل .conf',
  'Import an .ovpn file': 'وارد کردن فایل .ovpn',
  'Proxy address and login': 'نشانی پراکسی و ورود',
  'Server, key and login': 'سرور، کلید و ورود',
  'VPN · one node, direct': 'VPN · یک گره، مستقیم',
  Traffic: 'ترافیک',
  'Connected for': 'مدت اتصال',
  'Turn off VPN': 'خاموش کردن VPN',
  'Turn on VPN': 'روشن کردن VPN',
  'Add a node in the Node tab to get started.': 'برای شروع، در زبانه گره یک گره اضافه کنید.',
  'The VPN is paused for your game': 'VPN به خاطر بازی شما متوقف شده است',
  'Game traffic settings': 'تنظیمات ترافیک بازی',
  'Your game session is running and takes priority': 'اتصال بازی شما فعال است و اولویت دارد',
  'Apps you selected for the game always use the game session, even if they are also listed here. Everything else you select below uses the VPN.':
    'برنامه‌هایی که برای بازی انتخاب کرده‌اید همیشه از اتصال بازی استفاده می‌کنند، حتی اگر اینجا هم فهرست شده باشند. هر چیز دیگری که در پایین انتخاب کنید از VPN استفاده می‌کند.',
  'Your game session is carrying all traffic. The VPN resumes when it stops or switches to split mode.':
    'اتصال بازی شما همه ترافیک را منتقل می‌کند. VPN پس از توقف آن یا رفتن به حالت تفکیکی ادامه می‌یابد.',
  'Add your VPN node': 'گره VPN خود را اضافه کنید',
  'One node, connected directly. No relay needed.': 'یک گره با اتصال مستقیم. به رله نیازی نیست.',
  'Choose the kind of VPN node': 'نوع گره VPN را انتخاب کنید',
  'VPN node': 'گره VPN',
  'Carrying your selected traffic': 'در حال انتقال ترافیک انتخاب‌شده',
  'Used the next time the VPN turns on': 'دفعه بعد که VPN روشن شود استفاده می‌شود',
  Replace: 'جایگزینی',
  'Confirm remove': 'تأیید حذف',
  'Choose what uses the VPN': 'انتخاب کنید چه چیزی از VPN استفاده کند',
  'Changing these while the VPN is on reconnects it once.':
    'تغییر این موارد هنگام روشن بودن VPN، یک بار آن را دوباره متصل می‌کند.',
  'VPN routing mode': 'حالت مسیریابی VPN',
  'Selected apps': 'برنامه‌های انتخاب‌شده',
  'Everything else stays normal': 'بقیه عادی می‌مانند',
  'All traffic': 'همه ترافیک',
  'Except your game': 'به جز بازی شما',
  'Resolve names through the VPN': 'تبدیل نام‌ها از طریق VPN',
  'Stop resolving names through the VPN': 'توقف تبدیل نام‌ها از طریق VPN',
  'Website names are looked up through the VPN, so a filtered local resolver cannot send you to a blocked or fake address. A running game session with this on handles lookups first.':
    'نام وب‌سایت‌ها از طریق VPN جستجو می‌شوند تا تبدیل‌کننده فیلترشده محلی نتواند شما را به نشانی مسدود یا جعلی بفرستد. اگر اتصال بازی با این گزینه فعال باشد، ابتدا آن جستجوها را انجام می‌دهد.',
  'Lookups use the resolver this PC normally uses. Turn this on if sites fail to open while the VPN is connected.':
    'جستجوها از تبدیل‌کننده معمول این رایانه استفاده می‌کنند. اگر سایت‌ها با VPN متصل باز نمی‌شوند، این را روشن کنید.',
  'Kill switch': 'قطع‌کننده اضطراری',
  'While the node is not answering, apps you selected are blocked instead of using your normal connection. Name lookups are never blocked.':
    'تا وقتی گره پاسخ نمی‌دهد، برنامه‌های انتخاب‌شده به جای استفاده از اتصال عادی مسدود می‌شوند. جستجوی نام هرگز مسدود نمی‌شود.',
  'While the node is not answering, apps you selected use your normal connection until it is back.':
    'تا وقتی گره پاسخ نمی‌دهد، برنامه‌های انتخاب‌شده تا بازگشت آن از اتصال عادی استفاده می‌کنند.',
  'Turn off the VPN kill switch': 'خاموش کردن قطع‌کننده اضطراری VPN',
  'Turn on the VPN kill switch': 'روشن کردن قطع‌کننده اضطراری VPN',
  'Apps and websites': 'برنامه‌ها و وب‌سایت‌ها',
  'All traffic uses the VPN, so this list is not needed right now.':
    'همه ترافیک از VPN عبور می‌کند، پس فعلاً به این فهرست نیازی نیست.',
  'Add app': 'افزودن برنامه',
  'Add folder': 'افزودن پوشه',
  'Add website or IP': 'افزودن وب‌سایت یا IP',
  'An L2TP/IPsec node routes by address, so it can carry websites and IP ranges but not individual apps. Use all-traffic mode, or a WireGuard, OpenVPN or SOCKS5 node, for apps.':
    'گره L2TP/IPsec بر اساس نشانی مسیریابی می‌کند، پس می‌تواند وب‌سایت‌ها و بازه‌های IP را منتقل کند اما نه برنامه‌های جداگانه را. برای برنامه‌ها از حالت همه ترافیک یا گره WireGuard، OpenVPN یا SOCKS5 استفاده کنید.',
  'Nothing selected yet': 'هنوز چیزی انتخاب نشده است',
  'Add the apps and websites that should use the VPN. Everything else keeps your normal connection.':
    'برنامه‌ها و وب‌سایت‌هایی را که باید از VPN استفاده کنند اضافه کنید. بقیه از اتصال عادی شما استفاده می‌کنند.',
  'Game rule wins': 'قانون بازی اولویت دارد',
  'Not routable by this node': 'این گره نمی‌تواند مسیریابی کند',
  Folder: 'پوشه',
  Website: 'وب‌سایت',
  'IP range': 'بازه IP',
  'IP address': 'نشانی IP',
  'VPN target': 'مقصد VPN',
  'Matching traffic goes through your VPN node. Your game session still comes first for anything it selects.':
    'ترافیک منطبق از گره VPN شما عبور می‌کند. اتصال بازی همچنان برای هر چیزی که انتخاب کرده اولویت دارد.',
  'Choose an application': 'یک برنامه انتخاب کنید',
  'Choose a folder': 'یک پوشه انتخاب کنید',
  'Select its .exe file': 'فایل .exe آن را انتخاب کنید',
  'Every application inside will match': 'همه برنامه‌های داخل آن منطبق می‌شوند',
  'Website or hostname': 'وب‌سایت یا نام میزبان',
  'IP or CIDR range': 'IP یا بازه CIDR',
  'Add target': 'افزودن مقصد',
  'Add a VPN target': 'افزودن مقصد VPN',
  'An L2TP/IPsec node in split mode routes by address only':
    'گره L2TP/IPsec در حالت تفکیکی فقط بر اساس نشانی مسیریابی می‌کند',
  'Add a node to use it beside your game': 'یک گره اضافه کنید تا کنار بازی از آن استفاده کنید',
  'VPN connected': 'VPN متصل است',
  'Available in the installed app.': 'در نسخه نصب‌شده در دسترس است.',
  'Game session on': 'اتصال بازی روشن است',
  'Game session starting': 'اتصال بازی در حال شروع است',
  'VPN on': 'VPN روشن است',
  'VPN connecting': 'VPN در حال اتصال است',
  'VPN paused for your game': 'VPN به خاطر بازی شما متوقف شده است',
  'Everything the VPN carries is forwarded to this proxy, TCP and UDP alike. Name lookups go over TCP through it, so they work even when the proxy has no UDP support.':
    'هر چه VPN منتقل می‌کند، چه TCP و چه UDP، به این پراکسی فرستاده می‌شود. جستجوی نام‌ها از طریق TCP و همین پراکسی انجام می‌شود، پس حتی بدون پشتیبانی UDP کار می‌کند.',
  'The VPN uses the Windows L2TP/IPsec client. In split mode it routes websites and IP ranges; for individual apps use all-traffic mode or another kind of node.':
    'VPN از کلاینت L2TP/IPsec ویندوز استفاده می‌کند. در حالت تفکیکی وب‌سایت‌ها و بازه‌های IP را مسیریابی می‌کند؛ برای برنامه‌های جداگانه از حالت همه ترافیک یا نوع دیگری از گره استفاده کنید.',
  'WireGuard node saved for the VPN.': 'گره WireGuard برای VPN ذخیره شد.',
  'Add a VPN node first.': 'ابتدا یک گره VPN اضافه کنید.',
  'Add at least one app or website for the VPN, or switch it to all traffic.':
    'دست‌کم یک برنامه یا وب‌سایت برای VPN اضافه کنید، یا آن را روی همه ترافیک بگذارید.',
  'The node has stopped answering. Selected apps are blocked until it is back.':
    'گره دیگر پاسخ نمی‌دهد. برنامه‌های انتخاب‌شده تا بازگشت آن مسدود هستند.',
  'The node has stopped answering. Selected apps use your normal connection until it is back.':
    'گره دیگر پاسخ نمی‌دهد. برنامه‌های انتخاب‌شده تا بازگشت آن از اتصال عادی استفاده می‌کنند.',
  'An L2TP/IPsec VPN routes by address, so it cannot select applications or folders. Use a website or IP target, all-traffic mode, or a WireGuard/OpenVPN node.':
    'VPN با L2TP/IPsec بر اساس نشانی مسیریابی می‌کند، پس نمی‌تواند برنامه یا پوشه انتخاب کند. از مقصد وب‌سایت یا IP، حالت همه ترافیک، یا گره WireGuard/OpenVPN استفاده کنید.',
  'An L2TP/IPsec VPN cannot follow wildcard names. Use an exact hostname or an IP range.':
    'VPN با L2TP/IPsec نمی‌تواند نام‌های عام را دنبال کند. از نام میزبان دقیق یا بازه IP استفاده کنید.',
  'Console sharing': 'اشتراک با کنسول',
  'Let a console or another device use this session through a proxy.':
    'اجازه دهید کنسول یا دستگاه دیگری از طریق پراکسی از این اتصال استفاده کند.',
  'Track tunnel usage over time, by node, application and device.':
    'مصرف تونل را بر اساس زمان، گره، برنامه و دستگاه ببینید.',
  'LAN proxy · SOCKS5 and HTTP': 'پراکسی شبکه محلی · SOCKS5 و HTTP',
  'Sharing is off': 'اشتراک خاموش است',
  'Turn it on to let a console, phone or another PC use this session.':
    'آن را روشن کنید تا کنسول، گوشی یا رایانه دیگری از این اتصال استفاده کند.',
  'The proxy did not start': 'پراکسی راه‌اندازی نشد',
  'Check the port and try again.': 'درگاه را بررسی کرده و دوباره تلاش کنید.',
  'Devices can connect': 'دستگاه‌ها می‌توانند متصل شوند',
  "Point a device's proxy setting at this PC. Its traffic goes through the session, whatever the split-tunnel rules say.":
    'تنظیم پراکسی دستگاه را روی این رایانه قرار دهید. ترافیک آن، مستقل از قوانین تونل تفکیکی، از اتصال عبور می‌کند.',
  'Ready for the next session': 'آماده برای اتصال بعدی',
  Error: 'خطا',
  Listening: 'در حال گوش دادن',
  'Waiting for session': 'در انتظار اتصال',
  'Share this session on the local network': 'اشتراک این اتصال در شبکه محلی',
  Port: 'درگاه',
  'SOCKS5 link': 'پیوند SOCKS5',
  'No network found': 'شبکه‌ای پیدا نشد',
  'Also reachable at': 'همچنین در دسترس از',
  'TCP and UDP': 'TCP و UDP',
  'Name lookups through the tunnel': 'جستجوی نام از طریق تونل',
  'Local network only': 'فقط شبکه محلی',
  Live: 'زنده',
  'Connected devices': 'دستگاه‌های متصل',
  Device: 'دستگاه',
  Open: 'باز',
  Now: 'اکنون',
  'This session': 'این اتصال',
  Idle: 'بیکار',
  Upload: 'ارسال',
  Download: 'دریافت',
  'No device has connected yet. Enter the address and port above in its proxy settings.':
    'هنوز دستگاهی متصل نشده است. نشانی و درگاه بالا را در تنظیمات پراکسی آن وارد کنید.',
  'The proxy is not running, so no device can connect.': 'پراکسی اجرا نمی‌شود، پس هیچ دستگاهی نمی‌تواند متصل شود.',
  'Devices appear here while a session is running.': 'دستگاه‌ها هنگام اجرای اتصال اینجا نمایش داده می‌شوند.',
  'Port and login': 'درگاه و ورود',
  'Login on': 'ورود فعال',
  'No login': 'بدون ورود',
  'If another program holds this port, the next free one is used instead.':
    'اگر برنامه دیگری از این درگاه استفاده کند، درگاه آزاد بعدی به کار می‌رود.',
  Username: 'نام کاربری',
  Optional: 'اختیاری',
  Password: 'گذرواژه',
  'Leave empty for no login': 'برای بدون ورود خالی بگذارید',
  'Saved — type to replace': 'ذخیره شده — برای جایگزینی تایپ کنید',
  'Required with a username': 'همراه نام کاربری لازم است',
  'Show password': 'نمایش گذرواژه',
  'Hide password': 'پنهان کردن گذرواژه',
  'The password is encrypted by Windows and changes apply without reconnecting.':
    'گذرواژه با ویندوز رمزنگاری می‌شود و تغییرات بدون اتصال دوباره اعمال می‌شوند.',
  'Choose a port from 1 to 65535.': 'درگاهی بین ۱ تا ۶۵۵۳۵ انتخاب کنید.',
  'Enter a password, or leave the username empty to turn the login off.':
    'گذرواژه را وارد کنید یا برای خاموش کردن ورود، نام کاربری را خالی بگذارید.',
  Setup: 'راه‌اندازی',
  'Connect a device': 'اتصال یک دستگاه',
  'Device type': 'نوع دستگاه',
  PlayStation: 'پلی‌استیشن',
  'Nintendo Switch': 'نینتندو سوییچ',
  Xbox: 'ایکس‌باکس',
  'PC and phone': 'رایانه و گوشی',
  'Settings → Network → Settings → Set Up Internet Connection.':
    'Settings ← Network ← Settings ← Set Up Internet Connection.',
  'Highlight your network, press Options, then choose Advanced Settings.':
    'شبکه خود را انتخاب کنید، دکمه Options را بزنید و سپس Advanced Settings را انتخاب کنید.',
  'System Settings → Internet → Internet Settings, then choose your network.':
    'System Settings ← Internet ← Internet Settings و سپس شبکه خود را انتخاب کنید.',
  'Change Settings → Proxy Settings → On.': 'Change Settings ← Proxy Settings ← On.',
  'Xbox has no proxy setting of its own.': 'ایکس‌باکس تنظیم پراکسی ندارد.',
  'Connect it through a router or device that can forward its traffic to a SOCKS5 proxy, such as a router running a tun2socks or Clash client.':
    'آن را از طریق روتر یا دستگاهی متصل کنید که بتواند ترافیک را به پراکسی SOCKS5 بفرستد، مانند روتری با کلاینت tun2socks یا Clash.',
  'Use any SOCKS5 client, or the system proxy setting for apps that only need TCP.':
    'از هر کلاینت SOCKS5 استفاده کنید، یا برای برنامه‌هایی که فقط TCP لازم دارند از پراکسی سیستم.',
  'Turn on UDP relay and remote DNS in the client, so games and name lookups use the tunnel too.':
    'در کلاینت، رله UDP و DNS راه دور را روشن کنید تا بازی‌ها و جستجوی نام هم از تونل عبور کنند.',
  'A console proxy setting uses HTTP, which carries TCP: sign-in, the store, downloads and most matchmaking. Game traffic sent over UDP still leaves directly. For full UDP, use a SOCKS5 client on a router in front of the console.':
    'تنظیم پراکسی کنسول از HTTP استفاده می‌کند که فقط TCP را منتقل می‌کند: ورود، فروشگاه، دانلودها و بیشتر مچ‌میکینگ. ترافیک UDP بازی همچنان مستقیم خارج می‌شود. برای UDP کامل، از کلاینت SOCKS5 روی روتری جلوی کنسول استفاده کنید.',
  'SOCKS5 carries TCP and UDP. Every connection, datagram and name lookup goes through the session, whatever the split-tunnel rules say.':
    'SOCKS5 هم TCP و هم UDP را منتقل می‌کند. هر اتصال، دیتاگرام و جستجوی نام، مستقل از قوانین تونل تفکیکی، از اتصال عبور می‌کند.',
  'Opens with the next session': 'با اتصال بعدی باز می‌شود',
  Devices: 'دستگاه‌ها',
  'LAN proxy saved.': 'پراکسی شبکه محلی ذخیره شد.',
  'LAN proxy updated. The session stayed connected.': 'پراکسی شبکه محلی به‌روز شد. اتصال برقرار ماند.',
  'Devices using the proxy': 'دستگاه‌های استفاده‌کننده از پراکسی',
  Workspace: 'محیط کار',
  Overview: 'نمای کلی',
  Node: 'گره',
  'The one node the VPN connects through.': 'تنها گرهی که VPN از طریق آن متصل می‌شود.',
  'No node yet': 'هنوز گرهی نیست',
  Protection: 'حفاظت',
  'Kill switch on': 'قطع‌کننده اضطراری روشن',
  'Kill switch off': 'قطع‌کننده اضطراری خاموش',
  'Names resolved through the VPN': 'نام‌ها از طریق VPN یافته می‌شوند',
  'Names resolved by this PC': 'نام‌ها توسط این رایانه یافته می‌شوند',
  'Turn on the VPN to see the apps and destinations it carries.':
    'VPN را روشن کنید تا برنامه‌ها و مقصدهایی را که منتقل می‌کند ببینید.',
  'Open an app you selected for the VPN to see its connections here.':
    'برنامه‌ای را که برای VPN انتخاب کرده‌اید باز کنید تا اتصال‌هایش اینجا دیده شود.',
  'In all-traffic mode the VPN carries everything except your game, so connections are not listed per app.':
    'در حالت همه ترافیک، VPN همه چیز به جز بازی شما را منتقل می‌کند، پس اتصال‌ها به تفکیک برنامه فهرست نمی‌شوند.',
  'Game sections': 'بخش‌های بازی',
  'VPN sections': 'بخش‌های VPN',
  Active: 'فعال',
  Waiting: 'در انتظار',
  'Needs attention': 'نیاز به بررسی',
  'Choose which apps and websites use the VPN, and how it behaves when the node goes quiet.':
    'انتخاب کنید کدام برنامه‌ها و وب‌سایت‌ها از VPN استفاده کنند و وقتی گره پاسخ نمی‌دهد چه رفتاری داشته باشد.',
  'Routes and nodes': 'مسیرها و گره‌ها',
  'Split tunnel': 'تونل تفکیکی',
  Connection: 'اتصال',
  Statistics: 'آمار',
  Settings: 'تنظیمات',
  Info: 'اطلاعات',
  'About GamePath and its creator.': 'درباره GamePath و سازنده آن.',
  Language: 'زبان',
  'Choose the interface language.': 'زبان رابط کاربری را انتخاب کنید.',
  'Local protection': 'حفاظت محلی',
  'Keys secured by Windows': 'کلیدها با ویندوز محافظت می‌شوند',
  Client: 'کلاینت',
  'Alpha build': 'نسخه آزمایشی',
  'GamePath client': 'کلاینت GamePath',
  'Loading GamePath…': 'در حال بارگذاری GamePath…',
  'Session control and live route telemetry.': 'کنترل اتصال و پایش زنده مسیرها.',
  'Add WireGuard, OpenVPN, L2TP/IPsec or SOCKS5 nodes GamePath can use.':
    'گره‌های WireGuard، OpenVPN، L2TP/IPsec یا SOCKS5 را اضافه کنید.',
  'Choose exactly which traffic should enter the multipath tunnel.': 'مشخص کنید کدام ترافیک وارد تونل چندمسیره شود.',
  'Choose how your traffic leaves this PC.': 'روش خروج ترافیک از این رایانه را انتخاب کنید.',
  'Track tunnel usage over time, by node and application.': 'مصرف تونل را بر اساس زمان، گره و برنامه ببینید.',
  'Control startup, diagnostics, and client behavior.': 'راه‌اندازی، عیب‌یابی و رفتار کلاینت را تنظیم کنید.',
  'Direct session': 'اتصال مستقیم',
  'Multipath session': 'اتصال چندمسیره',
  'Traffic is routing': 'ترافیک در حال مسیریابی است',
  'Paths connected': 'مسیرها متصل‌اند',
  'Ready to accelerate': 'آماده اتصال',
  'Complete your setup': 'راه‌اندازی را کامل کنید',
  'Active node': 'گره فعال',
  'Active routes': 'مسیرهای فعال',
  'Node latency': 'تأخیر گره',
  'Best route': 'بهترین مسیر',
  'Packet loss': 'افت بسته',
  'Loss repair': 'ترمیم افت بسته',
  'Automatic relay failover': 'جابه‌جایی خودکار رله',
  'Standby relay': 'رله پشتیبان',
  'First other ready relay': 'اولین رله آماده دیگر',
  'Available in relay mode.': 'در حالت رله در دسترس است.',
  'Set up a second relay to use as a standby.': 'برای استفاده به‌عنوان پشتیبان، یک رله دوم راه‌اندازی کنید.',
  'If your relay stops answering through every node for 30 seconds while your internet works, this session moves to the standby relay. It never moves back by itself. Applies from the next session.':
    'اگر رله شما در حالی که اینترنتتان کار می‌کند، ۳۰ ثانیه از هیچ گرهی پاسخ ندهد، این اتصال به رله پشتیبان منتقل می‌شود. هرگز خودکار برنمی‌گردد. از اتصال بعدی اعمال می‌شود.',
  'Rebuilds a packet lost on every path from a small repair packet':
    'بسته‌ای را که در همه مسیرها از دست رفته، با یک بسته ترمیم کوچک بازسازی می‌کند',
  'Relay mode only': 'فقط در حالت رله',
  'Update the relay to enable': 'برای فعال‌سازی، رله را به‌روزرسانی کنید',
  Starting: 'در حال آغاز',
  'Start session': 'شروع اتصال',
  'Stop session': 'قطع اتصال',
  'Starting…': 'در حال اتصال…',
  'Direct · one node': 'مستقیم · یک گره',
  'Relay · adaptive duplication': 'رله · ارسال تطبیقی چندمسیره',
  'Choose a tunnelling node': 'یک گره تونل انتخاب کنید',
  'Add a VPN route': 'یک مسیر VPN اضافه کنید',
  'Choose traffic mode': 'حالت ترافیک را انتخاب کنید',
  'All IPv4 system traffic': 'تمام ترافیک IPv4 سیستم',
  'Configure a relay': 'رله را تنظیم کنید',
  'No relay selected': 'رله‌ای انتخاب نشده است',
  Configure: 'تنظیم',
  'Set up': 'راه‌اندازی',
  'Game server': 'سرور بازی',
  Relay: 'رله',
  'Your game': 'بازی شما',
  'Path overview': 'نمای مسیر',
  'Setup checklist': 'فهرست راه‌اندازی',
  'Manage routes': 'مدیریت مسیرها',
  'Live telemetry': 'پایش زنده',
  'Network journey': 'مسیر شبکه',
  'Journey breakdown': 'جزئیات مسیر',
  'Route latency history': 'تاریخچه تأخیر مسیر',
  Latency: 'تأخیر',
  Jitter: 'نوسان تأخیر',
  'Probe loss': 'افت بسته‌های آزمایشی',
  'Last 60 received probe samples · refreshed every 2s': '۶۰ نمونه اخیر · به‌روزرسانی هر ۲ ثانیه',
  'Start a session to measure every enabled WireGuard route.': 'برای سنجش مسیرهای فعال WireGuard اتصال را شروع کنید.',
  'No nodes yet': 'هنوز گره‌ای ندارید',
  'New group': 'گروه جدید',
  'Import .conf': 'وارد کردن .conf',
  'Add nodes': 'افزودن گره',
  'Group these nodes': 'این گره‌ها را گروه‌بندی کنید',
  'Put a fleet under one switch so you can pause all of it at once.':
    'گره‌ها را زیر یک کلید قرار دهید تا همگی را با هم متوقف کنید.',
  'Your VPN secrets stay on this PC': 'اطلاعات محرمانه VPN روی همین رایانه می‌ماند',
  'GamePath only decrypts a configuration or login when the local network service needs it.':
    'GamePath پیکربندی یا اطلاعات ورود را فقط هنگام نیاز سرویس شبکه محلی رمزگشایی می‌کند.',
  'These answer to their own switch': 'این موارد کلید مستقل دارند',
  'Direct mode uses one node, so switching this group on picks a single node.':
    'حالت مستقیم از یک گره استفاده می‌کند؛ روشن کردن این گروه فقط یک گره را انتخاب می‌کند.',
  'Relay fleet': 'رله‌ها',
  'Add your VPS locations and enable one relay at a time.': 'مکان‌های VPS را اضافه کنید و هر بار یک رله را فعال کنید.',
  'More regions are planned': 'مناطق بیشتری در راه است',
  'Relay mode': 'حالت رله',
  'Direct mode': 'حالت مستقیم',
  'Lowest loss': 'کمترین افت',
  'No server needed': 'بدون نیاز به سرور',
  'Needs a VPS running the GamePath relay.': 'به VPS با رله GamePath نیاز دارد.',
  'Needs one tunnelling node. SOCKS5 proxies can only be used with a relay.':
    'به یک گره تونل نیاز دارد. پراکسی SOCKS5 فقط با رله کار می‌کند.',
  'Suits your setup': 'مناسب تنظیمات شما',
  'Switch to relay mode': 'تغییر به حالت رله',
  'Routing scope': 'دامنه مسیریابی',
  'Choose what enters GamePath': 'انتخاب ترافیک ورودی به GamePath',
  'Switch modes at any time before starting a session.': 'پیش از شروع اتصال، هر زمان می‌توانید حالت را تغییر دهید.',
  'Selected targets': 'مقصدهای انتخاب‌شده',
  'Whole system': 'کل سیستم',
  'Resolve names through the tunnel': 'حل نام‌ها از طریق تونل',
  'All-IPv4-traffic mode is active': 'حالت تمام ترافیک IPv4 فعال است',
  'IPv6 is not carried': 'ترافیک IPv6 منتقل نمی‌شود',
  'Split group': 'گروه تفکیکی',
  Target: 'مقصد',
  Type: 'نوع',
  Destination: 'مقصد',
  Group: 'گروه',
  Status: 'وضعیت',
  'This group is ready for targets': 'این گروه آماده افزودن مقصد است',
  'Add an app, folder, hostname, or IP range. You can move targets between groups later.':
    'برنامه، پوشه، نام میزبان یا بازه IP اضافه کنید. بعداً می‌توانید مقصدها را جابه‌جا کنید.',
  'Removing this group keeps its targets in Ungrouped.': 'با حذف گروه، مقصدهای آن در «بدون گروه» می‌مانند.',
  'Open a group to manage its traffic targets.': 'برای مدیریت مقصدهای ترافیک، گروه را باز کنید.',
  Ungrouped: 'بدون گروه',
  'Ungrouped targets': 'مقصدهای بدون گروه',
  'Move these into a group anytime': 'هر زمان می‌توانید آن‌ها را به گروه منتقل کنید',
  'Create another group': 'ساخت گروه دیگر',
  'Bundle targets under one on/off switch': 'مقصدها را زیر یک کلید روشن/خاموش جمع کنید',
  'Create your first split group': 'اولین گروه تفکیکی را بسازید',
  'Keep each game and its related services together, then turn the whole group on or off.':
    'هر بازی و سرویس‌های مرتبط را کنار هم بگذارید و کل گروه را روشن یا خاموش کنید.',
  'Traffic rule': 'قانون ترافیک',
  'Add a split-tunnel target': 'افزودن مقصد تونل تفکیکی',
  'Groups let you pause a whole game or workflow without changing its individual targets.':
    'گروه‌ها امکان توقف یک بازی یا جریان کار را بدون تغییر مقصدهای تکی فراهم می‌کنند.',
  Paused: 'متوقف',
  Enabled: 'فعال',
  Disabled: 'غیرفعال',
  Off: 'خاموش',
  On: 'روشن',
  'Carrying traffic': 'در حال انتقال ترافیک',
  Carrying: 'در حال انتقال',
  'Needs a relay': 'به رله نیاز دارد',
  'Paused by group': 'با گروه متوقف شده',
  Transport: 'انتقال',
  Auth: 'احراز هویت',
  Encryption: 'رمزنگاری',
  Secrets: 'اطلاعات محرمانه',
  Address: 'نشانی',
  Protected: 'محافظت‌شده',
  'Key protected': 'کلید محافظت‌شده',
  Certificate: 'گواهی',
  None: 'هیچ‌کدام',
  'Username and password': 'نام کاربری و رمز عبور',
  'Frames only': 'فقط بسته‌ها',
  'Windows RAS': 'Windows RAS',
  'PSK + username': 'PSK + نام کاربری',
  'UDP associate': 'ارتباط UDP',
  'Traffic over time': 'ترافیک در طول زمان',
  Today: 'امروز',
  'This week': 'این هفته',
  'This month': 'این ماه',
  'Current session usage': 'مصرف اتصال فعلی',
  'Session total': 'مجموع مصرف اتصال',
  'This year': 'امسال',
  'All time': 'همه زمان‌ها',
  Custom: 'دلخواه',
  'Reset statistics': 'پاک کردن آمار',
  From: 'از',
  To: 'تا',
  'Total carried': 'کل ترافیک منتقل‌شده',
  'Unique tunnelled IP traffic': 'ترافیک IP یکتای منتقل‌شده از تونل',
  Uploaded: 'ارسال‌شده',
  Downloaded: 'دریافت‌شده',
  'From this PC': 'از این رایانه',
  'To this PC': 'به این رایانه',
  Yearly: 'سالانه',
  Monthly: 'ماهانه',
  Weekly: 'هفتگی',
  Daily: 'روزانه',
  'usage in the selected range': 'مصرف در بازه انتخاب‌شده',
  Sent: 'ارسال',
  Received: 'دریافت',
  'No traffic recorded in this range yet.': 'هنوز ترافیکی در این بازه ثبت نشده است.',
  'View exact values': 'نمایش مقادیر دقیق',
  Period: 'دوره',
  'Behind GamePath': 'درباره GamePath',
  'Built by primemb': 'ساخته primemb',
  'A better path to your next game.': 'مسیری بهتر برای بازی بعدی شما.',
  Creator: 'سازنده',
  'GamePath on GitHub': 'GamePath در GitHub',
  'Connect on Discord': 'ارتباط در Discord',
  'Relay routing mode': 'روش مسیریابی رله',
  Smart: 'هوشمند',
  Manual: 'دستی',
  'Best two, more when unstable': 'دو مسیر برتر، بیشتر هنگام ناپایداری',
  'Every healthy route': 'همه مسیرهای سالم',
  'Start with Windows': 'اجرای هم‌زمان با ویندوز',
  'Open GamePath in the background after signing in.': 'پس از ورود به ویندوز، GamePath را در پس‌زمینه باز کنید.',
  'Local diagnostics': 'عیب‌یابی محلی',
  'Keep route latency and packet-loss history for troubleshooting.':
    'تاریخچه تأخیر مسیر و افت بسته را برای عیب‌یابی نگه دارید.',
  'Windows network capabilities': 'امکانات شبکه ویندوز',
  'Split-tunnel interception': 'رهگیری تونل تفکیکی',
  'GamePath Network Service': 'سرویس شبکه GamePath',
  'Reinstall service': 'نصب دوباره سرویس',
  'Install service': 'نصب سرویس',
  'Installing…': 'در حال نصب…',
  'Refresh status': 'به‌روزرسانی وضعیت',
  'Secure SSH setup': 'راه‌اندازی امن SSH',
  'Keep GamePath open. A first-time Rust build can take several minutes.':
    'GamePath را باز نگه دارید. ساخت اولیه Rust ممکن است چند دقیقه طول بکشد.',
  'SOCKS5 proxy': 'پراکسی SOCKS5',
  'Add a proxy node': 'افزودن گره پراکسی',
  'This proxy can carry GamePath traffic': 'این پراکسی می‌تواند ترافیک GamePath را منتقل کند',
  'This proxy cannot be used yet': 'این پراکسی هنوز قابل استفاده نیست',
  Save: 'ذخیره',
  Cancel: 'لغو',
  Close: 'بستن',
  Delete: 'حذف',
  Remove: 'برداشتن',
  Edit: 'ویرایش',
  Test: 'آزمایش',
  Add: 'افزودن',
  Back: 'بازگشت',
  Next: 'بعدی',
  Continue: 'ادامه',
  Ready: 'آماده',
  Loading: 'در حال بارگذاری',
  'Add node': 'افزودن گره',
  'Adding…': 'در حال افزودن…',
  'All applications inside will match': 'همه برنامه‌های داخل پوشه شامل می‌شوند',
  'All VPN nodes': 'همه گره‌های VPN',
  'Attention needed': 'نیاز به بررسی',
  'Auto-configure VPS': 'تنظیم خودکار VPS',
  'Available in relay mode. Direct mode always uses its one selected node.':
    'این گزینه در حالت رله فعال است. حالت مستقیم همیشه از یک گره انتخاب‌شده استفاده می‌کند.',
  'Awaiting route': 'در انتظار مسیر',
  'Awaiting target': 'در انتظار مقصد',
  'Benchmark RTT': 'زمان رفت‌وبرگشت آزمایش',
  'Bundle related apps, services, and destinations under one switch.':
    'برنامه‌ها، سرویس‌ها و مقصدهای مرتبط را زیر یک کلید جمع کنید.',
  'Carrying your traffic': 'در حال انتقال ترافیک شما',
  'Configure Linux VPS': 'تنظیم VPS لینوکس',
  'Configure VPS': 'تنظیم VPS',
  'Configuring VPS…': 'در حال تنظیم VPS…',
  'Relay already installed on this VPS': 'رله از قبل روی این VPS نصب شده است',
  'Skip the install and only enroll this PC. Takes a few seconds.':
    'نصب را رد کن و فقط این رایانه را ثبت کن. چند ثانیه طول می‌کشد.',
  'GamePath signs in to your VPS, enrolls this PC on the relay that is already running there, and restarts it once. Nothing is reinstalled.':
    'GamePath وارد VPS شما می‌شود، این رایانه را روی رله‌ای که از قبل آنجا اجرا می‌شود ثبت می‌کند و آن را یک بار راه‌اندازی مجدد می‌کند. چیزی دوباره نصب نمی‌شود.',
  'Enroll this PC': 'ثبت این رایانه',
  'Enrolling…': 'در حال ثبت…',
  'Preparing enrollment': 'در حال آماده‌سازی ثبت',
  'Enrolling this PC on the existing relay': 'در حال ثبت این رایانه روی رله موجود',
  'This PC is enrolled on the relay': 'این رایانه روی رله ثبت شد',
  'This PC is enrolled on the VPS relay and the credential is protected by Windows.':
    'این رایانه روی رله VPS ثبت شد و اعتبارنامه توسط ویندوز محافظت می‌شود.',
  'Could not copy the username. You can add prime_lifesoul on Discord.':
    'کپی نام کاربری ممکن نشد. می‌توانید prime_lifesoul را در Discord اضافه کنید.',
  'Could not load usage statistics.': 'بارگذاری آمار مصرف ممکن نشد.',
  'Could not reset statistics.': 'پاک کردن آمار ممکن نشد.',
  'Create a split group': 'ساخت گروه تفکیکی',
  'Create group': 'ساخت گروه',
  'Credential already protected — leave blank to keep it':
    'اطلاعات ورود محافظت شده است؛ برای نگه داشتن آن خالی بگذارید',
  'Credential protected': 'اطلاعات ورود محافظت‌شده',
  'Current path': 'مسیر فعلی',
  'Current route chain': 'زنجیره مسیر فعلی',
  'Delete all saved usage statistics? This cannot be undone.': 'همه آمار ذخیره‌شده حذف شود؟ این کار برگشت‌پذیر نیست.',
  'Direct mode sends your traffic through one WireGuard, OpenVPN or L2TP/IPsec node. SOCKS5 proxies need a relay.':
    'حالت مستقیم ترافیک را از یک گره WireGuard، OpenVPN یا L2TP/IPsec می‌فرستد. پراکسی SOCKS5 به رله نیاز دارد.',
  'Discord username copied: prime_lifesoul': 'نام کاربری Discord کپی شد: prime_lifesoul',
  'Each carrying node moves relay traffic through its own VPN or proxy hop. Group nodes to switch a whole set on or off at once.':
    'هر گره فعال ترافیک رله را از VPN یا پراکسی خودش می‌فرستد. برای روشن یا خاموش کردن چند گره با هم، آن‌ها را گروه‌بندی کنید.',
  'Every node you enable carries the same packets to a relay you run. When one hop stumbles, the copy that took the other path still arrives on time.':
    'هر گره فعال بسته‌های یکسان را به رله شما می‌رساند. اگر یک مسیر دچار مشکل شود، نسخه‌ای که از مسیر دیگر رفته همچنان می‌رسد.',
  'Frames are encrypted by GamePath, but the proxy hop itself is not':
    'بسته‌ها را GamePath رمزنگاری می‌کند، اما مسیر پراکسی به‌خودی‌خود رمزنگاری ندارد',
  'GamePath Network Service installed and running.': 'سرویس شبکه GamePath نصب و اجرا شد.',
  'GamePath was removed from the VPS.': 'GamePath از VPS حذف شد.',
  'Give this group a clear, recognizable name.': 'برای گروه نامی روشن و قابل تشخیص بگذارید.',
  'Group off': 'گروه خاموش',
  'Group on': 'گروه روشن',
  'It uses': 'استفاده می‌کند از',
  'Lookups use whatever resolver this PC normally uses. Turn this on if a game or site fails to connect while the tunnel itself is healthy.':
    'جست‌وجوی نام‌ها از DNS معمول این رایانه استفاده می‌کند. اگر تونل سالم است ولی بازی یا سایت وصل نمی‌شود، این گزینه را روشن کنید.',
  'Node quality': 'کیفیت گره',
  'Node, traffic mode and the current path': 'گره، حالت ترافیک و مسیر فعلی',
  'Not configured': 'تنظیم نشده',
  'One node, no duplication': 'یک گره، بدون ارسال چندگانه',
  'Preparing deployment': 'آماده‌سازی نصب',
  'Relay probe RTT': 'زمان رفت‌وبرگشت آزمایش رله',
  'Remove from VPS': 'حذف از VPS',
  'Remove relay from VPS': 'حذف رله از VPS',
  'Removing…': 'در حال حذف…',
  'Rename group': 'تغییر نام گروه',
  'Route quality': 'کیفیت مسیر',
  'Routes, traffic mode, relay and the current path chain': 'مسیرها، حالت ترافیک، رله و زنجیره مسیر فعلی',
  'Save changes': 'ذخیره تغییرات',
  'Saving…': 'در حال ذخیره…',
  'Select the game .exe file': 'فایل .exe بازی را انتخاب کنید',
  'Setup complete': 'راه‌اندازی کامل شد',
  'Setup required': 'راه‌اندازی لازم است',
  'Smart uses the best two healthy routes and adds more while one of them is unstable. Manual duplicates through every healthy enabled route. Changes apply when you next start a session.':
    'حالت هوشمند از دو مسیر سالم برتر استفاده می‌کند و وقتی یکی ناپایدار شود مسیرهای بیشتری اضافه می‌کند. حالت دستی بسته‌ها را از همه مسیرهای سالم و فعال می‌فرستد. تغییرات از اتصال بعدی اعمال می‌شوند.',
  'Something went wrong': 'مشکلی پیش آمد',
  'Stop resolving': 'توقف حل نام‌ها',
  'Target collection': 'مجموعه مقصدها',
  'Test connection': 'آزمایش اتصال',
  'Test UDP': 'آزمایش UDP',
  'Testing…': 'در حال آزمایش…',
  'The pre-shared key and password are protected by Windows secure storage':
    'کلید مشترک و رمز عبور با ذخیره‌سازی امن ویندوز محافظت می‌شوند',
  'The server assigns the address and the cipher when the session starts':
    'سرور هنگام شروع اتصال، نشانی و الگوریتم رمزنگاری را تعیین می‌کند',
  'The start date must be on or before the end date.': 'تاریخ شروع باید پیش از تاریخ پایان یا برابر با آن باشد.',
  'These files need a login': 'این فایل‌ها به اطلاعات ورود نیاز دارند',
  'They use': 'استفاده می‌کنند از',
  'This file needs a login': 'این فایل به اطلاعات ورود نیاز دارد',
  'This removes the GamePath service, firewall tables, configuration, clients, and binary from this server.':
    'با این کار سرویس GamePath، قوانین فایروال، تنظیمات، کلاینت‌ها و فایل اجرایی از این سرور حذف می‌شود.',
  'Traffic enabled': 'ترافیک فعال',
  'Traffic paused': 'ترافیک متوقف',
  'Ungrouped nodes': 'گره‌های بدون گروه',
  'Unknown application': 'برنامه ناشناس',
  'Update VPS': 'به‌روزرسانی VPS',
  'Usage statistics reset.': 'آمار مصرف پاک شد.',
  'Waiting for probes': 'در انتظار آزمایش مسیر',
  'Websites and game servers are looked up at the far end of the tunnel, so a filtered or poisoned local resolver cannot send you to the wrong address. Applies to every app on this PC, not only the ones you select.':
    'نام سایت‌ها و سرورهای بازی در انتهای تونل بررسی می‌شود تا DNS محلی فیلترشده یا دست‌کاری‌شده نشانی اشتباه برنگرداند. این تنظیم برای همه برنامه‌های این رایانه اعمال می‌شود.',
  'Your node': 'گره شما',
  'Your VPN node': 'گره VPN شما',
  'WireGuard, OpenVPN or L2TP/IPsec node': 'گره WireGuard، OpenVPN یا L2TP/IPsec',
  'Add a WireGuard, OpenVPN or L2TP/IPsec node from your VPN provider. Direct mode routes through it, so it is all you need. Secrets are protected with Windows secure storage.':
    'یک گره WireGuard، OpenVPN یا L2TP/IPsec از ارائه‌دهنده VPN خود اضافه کنید. حالت مستقیم از همان عبور می‌کند. اطلاعات محرمانه با ذخیره‌سازی امن ویندوز محافظت می‌شوند.',
  'Add a WireGuard, OpenVPN, L2TP/IPsec or SOCKS5 node. Private keys and passwords are protected with Windows secure storage.':
    'یک گره WireGuard، OpenVPN، L2TP/IPsec یا SOCKS5 اضافه کنید. کلیدهای خصوصی و رمزهای عبور با ذخیره‌سازی امن ویندوز محافظت می‌شوند.',
  'Your selected traffic goes through one WireGuard, OpenVPN or L2TP/IPsec node and out to the game from there. A plain split tunnel, with nothing else to run.':
    'ترافیک انتخاب‌شده از یک گره WireGuard، OpenVPN یا L2TP/IPsec عبور می‌کند و سپس به بازی می‌رسد. یک تونل تفکیکی ساده، بدون سرویس اضافی.',
  'Configure relay endpoint': 'تنظیم نشانی رله',
  'New location': 'مکان جدید',
  'Add relay server': 'افزودن سرور رله',
  'No group': 'بدون گروه',
  'Windows VPN': 'VPN ویندوز',
  'Add an L2TP/IPsec node': 'افزودن گره L2TP/IPsec',
  'The L2TP connection works': 'اتصال L2TP کار می‌کند',
  'Windows could not connect': 'ویندوز نتوانست وصل شود',
  'Route latency appears here as soon as a session is running.': 'با شروع اتصال، تأخیر مسیر اینجا نمایش داده می‌شود.',
  'Handled connections': 'اتصال‌های مدیریت‌شده',
  'Traffic currently routed': 'ترافیکی که اکنون مسیریابی می‌شود',
  'Start the game to see each executable and destination IP handled by GamePath.':
    'بازی را اجرا کنید تا هر برنامه و IP مقصدی که GamePath مدیریت می‌کند اینجا نمایش داده شود.',
  'Capture p99': 'رهگیری p99',
  'Pending SYN': 'SYN در انتظار',
  'Queue peak': 'اوج صف',
  Overflow: 'سرریز',
  Application: 'برنامه',
  Connections: 'اتصال‌ها',
  Protocols: 'پروتکل‌ها',
  Latest: 'آخرین',
  active: 'فعال',
  Protocol: 'پروتکل',
  Connected: 'متصل',
  'The node could not be added': 'افزودن گره ممکن نشد',
  Nodes: 'گره‌ها',
  Applications: 'برنامه‌ها',
  nodes: 'گره‌ها',
  applications: 'برنامه‌ها',
  'Statistics period': 'دوره آمار',
  'Traffic routing mode': 'حالت مسیریابی ترافیک',
  'Copy Discord username prime_lifesoul': 'کپی نام کاربری Discord: prime_lifesoul',
  'Removing the group keeps its nodes; they become ungrouped.':
    'با حذف گروه، گره‌های آن به بخش بدون گروه منتقل می‌شوند.',
  'e.g. Istanbul fleet': 'مثلاً گره‌های استانبول',
  'VPS configuration progress': 'پیشرفت تنظیم VPS',
  'Add a SOCKS5 node': 'افزودن گره SOCKS5',
  'Local proxy': 'پراکسی محلی',
  'Leave blank': 'خالی بگذارید',
  'Close group dialog': 'بستن پنجره گروه',
  'Add split tunnel target': 'افزودن مقصد تونل تفکیکی',
  'Close add target dialog': 'بستن پنجره افزودن مقصد',
  'Configure relay': 'تنظیم رله',
  'Enter the OpenVPN login': 'وارد کردن اطلاعات ورود OpenVPN',
  'The login from your provider': 'نام کاربری ارائه‌دهنده',
  'Stored encrypted and never shown again': 'رمزنگاری و ذخیره می‌شود و دوباره نمایش داده نمی‌شود',
  'Provider L2TP': 'ارائه‌دهنده L2TP',
  Required: 'الزامی',
  'Connection mode': 'حالت اتصال',
  'Latency history for every WireGuard route': 'تاریخچه تأخیر همه مسیرهای WireGuard',
  'Dismiss notification': 'بستن اعلان',
  ready: 'آماده',
  error: 'خطا',
  'not-installed': 'نصب نشده',
  'setup-required': 'نیازمند راه‌اندازی',
  idle: 'بیکار',
  'Native engine ready': 'موتور بومی آماده است',
  'Network service is not installed': 'سرویس شبکه نصب نشده است',
  'Privileged network service ready': 'سرویس شبکه آماده است',
  'Signed Wintun library is ready': 'کتابخانه امضاشده Wintun آماده است',
  'Signed WFP capture runtime is ready': 'سامانه رهگیری امضاشده WFP آماده است',
  'Remove VPS': 'حذف VPS',
}

const dynamic: [RegExp, (...parts: string[]) => string][] = [
  [/^(\d+) selected$/, (count) => `${count} انتخاب‌شده`],
  [
    /^Logged in to (.+) in (\d+) ms, and reached the Internet through it in (\d+) ms\.$/,
    (proxy, login, reach) =>
      `ورود به ${proxy} در ${login} میلی‌ثانیه، و دسترسی به اینترنت از طریق آن در ${reach} میلی‌ثانیه.`,
  ],
  [/^Stop sending (.+) through the VPN$/, (name) => `توقف ارسال ${name} از طریق VPN`],
  [/^Send (.+) through the VPN$/, (name) => `ارسال ${name} از طریق VPN`],
  [/^Connecting to (.+)…$/, (node) => `در حال اتصال به ${node}…`],
  [/^Reconnecting to (.+)…$/, (node) => `در حال اتصال دوباره به ${node}…`],
  [/^Connected through (.+)\.$/, (node) => `از طریق ${node} متصل است.`],
  [/^Through (.+)$/, (detail) => `از طریق ${detail}`],
  [/^(.+) is ready to connect\.?$/, (node) => `${node} آماده اتصال است`],
  [/^(.+) node saved for the VPN\.$/, (kind) => `گره ${kind} برای VPN ذخیره شد.`],
  [/^(.+) Retrying in (\d+) s\.$/, (reason, seconds) => `${reason} تلاش دوباره تا ${seconds} ثانیه دیگر.`],
  [
    /^Choose the new node\. It replaces (.+), and the VPN reconnects through it\.$/,
    (node) => `گره جدید را انتخاب کنید. جایگزین ${node} می‌شود و VPN از طریق آن دوباره متصل می‌شود.`,
  ],
  [/^Choose the new node\. It replaces (.+)\.$/, (node) => `گره جدید را انتخاب کنید. جایگزین ${node} می‌شود.`],
  [
    /^L2TP\/IPsec works: connected in (\d+) ms, data returned in (\d+) ms\.$/,
    (setup, data) => `L2TP/IPsec کار می‌کند: اتصال در ${setup} میلی‌ثانیه، بازگشت داده در ${data} میلی‌ثانیه.`,
  ],
  [/^Remove (.+)$/, (name) => `حذف ${name}`],
  [/^Delete (.+)$/, (name) => `حذف ${name}`],
  [/^Rename (.+)$/, (name) => `تغییر نام ${name}`],
  [/^Enable (.+)$/, (name) => `فعال کردن ${name}`],
  [/^Disable (.+)$/, (name) => `غیرفعال کردن ${name}`],
  [/^(\d+) targets? selected$/, (count) => `${count} مقصد انتخاب شده`],
  [/^Group for (.+)$/, (name) => `گروه ${name}`],
  [/^Carry traffic through (.+)$/, (name) => `انتقال ترافیک از ${name}`],
  [/^(.+) connection details$/, (name) => `جزئیات اتصال‌های ${name}`],
  [
    /^(\d+) of (\d+) requirements ready — finish Setup in Overview\.$/,
    (ready, total) => `${ready} از ${total} پیش‌نیاز آماده است؛ بخش راه‌اندازی را باز کنید.`,
  ],
  [
    /^(\d+) encrypted paths active through (.+)\.$/,
    (count, relay) => `${count} مسیر رمزنگاری‌شده از طریق ${relay} فعال است.`,
  ],
  [
    /^(\d+) routes will carry game traffic through (.+)\.$/,
    (count, relay) => `${count} مسیر ترافیک بازی را از طریق ${relay} می‌فرستد.`,
  ],
  [/^Selected traffic is going through (.+)\.$/, (node) => `ترافیک انتخاب‌شده از ${node} عبور می‌کند.`],
  [/^(.+) will carry your selected traffic\.$/, (node) => `${node} ترافیک انتخاب‌شده را منتقل می‌کند.`],
  [/^(.+) will carry your traffic$/, (node) => `${node} ترافیک شما را منتقل می‌کند`],
  [
    /^(\d+) routing nodes? added; pick exactly one$/,
    (count) => `${count} گره مسیریابی اضافه شده است؛ فقط یکی را انتخاب کنید`,
  ],
  [
    /^(\d+) nodes? added; the relay is reached only through carrying nodes$/,
    (count) => `${count} گره اضافه شده است؛ دسترسی به رله فقط از گره‌های فعال انجام می‌شود`,
  ],
  [/^(\d+) active split-tunnel targets?$/, (count) => `${count} مقصد فعال تونل تفکیکی`],
  [/^(\d+) of (\d+) nodes? carrying$/, (active, total) => `${active} از ${total} گره در حال انتقال`],
  [/^Paused · (\d+) nodes?$/, (count) => `متوقف · ${count} گره`],
  [/^(\d+) of (\d+) carrying$/, (active, total) => `${active} از ${total} فعال`],
  [/^(\d+) active routes?$/, (count) => `${count} مسیر فعال`],
  [/^(\d+) of (\d+) routes carrying traffic$/, (active, total) => `${active} از ${total} مسیر در حال انتقال ترافیک`],
  [/^(\d+) game packets routed$/, (count) => `${count} بسته بازی مسیریابی شد`],
  [
    /^The (.+) relay needs its address and enrollment token\.$/,
    (city) => `رله ${city} به نشانی و توکن ثبت‌نام نیاز دارد.`,
  ],
  [
    /^(.+) stopped answering, so this session moved to (.+)\. It stays there until you start a new session\.$/,
    (from, to) => `${from} پاسخ نداد، پس این اتصال به ${to} منتقل شد. تا شروع اتصال بعدی همان‌جا می‌ماند.`,
  ],
  [/^Moving to (.+)…$/, (city) => `در حال انتقال به ${city}…`],
  [/^Moved to (.+) after (.+) stopped answering\.$/, (to, from) => `پس از پاسخ ندادن ${from}، به ${to} منتقل شد.`],
  [
    /^1 repair per (\d+) packets · (\d+) rebuilt$/,
    (group, rebuilt) => `یک بسته ترمیم برای هر ${group} بسته · ${rebuilt} بازسازی‌شده`,
  ],
  [/^(\d+) tracked$/, (count) => `${count} مورد ثبت‌شده`],
  [/^(\d+) files could not be added$/, (count) => `افزودن ${count} فایل ممکن نشد`],
  [/^Add (\d+) nodes$/, (count) => `افزودن ${count} گره`],
  [/^Setup — (\d+) of (\d+) ready$/, (ready, total) => `راه‌اندازی — ${ready} از ${total} آماده`],
  [/^(\d+) active · (\d+) targets$/, (active, total) => `${active} فعال · ${total} مقصد`],
  [
    /^No (.+) usage in this range\.$/,
    (category) => `در این بازه مصرفی برای ${translatePersian(category)} ثبت نشده است.`,
  ],
  [/^(.+) · VPS not configured$/, (country) => `${country} · VPS تنظیم نشده است`],
  [
    /^(\d+) active connections? · (\d+) applications?$/,
    (connections, applications) => `${connections} اتصال فعال · ${applications} برنامه`,
  ],
  [/^(\d+) connected$/, (count) => `${count} متصل`],
  [/^(\d+) devices? connected$/, (count) => `${count} دستگاه متصل`],
  [/^Port (\d+)$/, (port) => `درگاه ${port}`],
  [
    /^Port (\d+) was in use, so the proxy took (\d+)\.$/,
    (requested, port) => `درگاه ${requested} در حال استفاده بود، پس پراکسی درگاه ${port} را گرفت.`,
  ],
  [
    /^The proxy opens on port (\d+) as soon as you start a session\.$/,
    (port) => `پراکسی به محض شروع اتصال روی درگاه ${port} باز می‌شود.`,
  ],
  [/^Copy (.+)$/, (label) => `کپی ${translatePersian(label)}`],
  [/^(.+) copied$/, (label) => `${translatePersian(label)} کپی شد`],
  [/^Version (.+)$/, (version) => `نسخه ${version}`],
  [/^Client (.+) · Alpha build$/, (version) => `کلاینت ${version} · نسخه آزمایشی`],
  [/^Engine (.+) ready$/, (version) => `موتور ${version} آماده است`],
]

export function translatePersian(value: string) {
  const exact = persian[value]
  if (exact) return exact
  for (const [pattern, render] of dynamic) {
    const match = value.match(pattern)
    if (match) return render(...match.slice(1))
  }
  return value
}
