export const persian: Record<string, string> = {
  Workspace: 'محیط کار',
  Overview: 'نمای کلی',
  'Routes and nodes': 'مسیرها و گره‌ها',
  'Split tunnel': 'تونل تفکیکی',
  Connection: 'اتصال',
  Statistics: 'آمار',
  Settings: 'تنظیمات',
  Info: 'اطلاعات',
  'About GamePath and its creator.': 'درباره GamePath و سازنده آن.',
  Language: 'زبان',
  'Choose the interface language.': 'زبان رابط کاربری را انتخاب کنید.',
  'Local protection': 'حفاظت محلی',
  'Keys secured by Windows': 'کلیدها با ویندوز محافظت می‌شوند',
  Client: 'کلاینت',
  'Alpha build': 'نسخه آزمایشی',
  'GamePath client': 'کلاینت GamePath',
  'Loading GamePath…': 'در حال بارگذاری GamePath…',
  'Session control and live route telemetry.': 'کنترل اتصال و پایش زنده مسیرها.',
  'Add WireGuard, OpenVPN, L2TP/IPsec or SOCKS5 nodes GamePath can use.':
    'گره‌های WireGuard، OpenVPN، L2TP/IPsec یا SOCKS5 را اضافه کنید.',
  'Choose exactly which traffic should enter the multipath tunnel.': 'مشخص کنید کدام ترافیک وارد تونل چندمسیره شود.',
  'Choose how your traffic leaves this PC.': 'روش خروج ترافیک از این رایانه را انتخاب کنید.',
  'Track tunnel usage over time, by node and application.': 'مصرف تونل را بر اساس زمان، گره و برنامه ببینید.',
  'Control startup, diagnostics, and client behavior.': 'راه‌اندازی، عیب‌یابی و رفتار کلاینت را تنظیم کنید.',
  'Direct session': 'اتصال مستقیم',
  'Multipath session': 'اتصال چندمسیره',
  'Traffic is routing': 'ترافیک در حال مسیریابی است',
  'Paths connected': 'مسیرها متصل‌اند',
  'Ready to accelerate': 'آماده اتصال',
  'Complete your setup': 'راه‌اندازی را کامل کنید',
  'Active node': 'گره فعال',
  'Active routes': 'مسیرهای فعال',
  'Node latency': 'تأخیر گره',
  'Best route': 'بهترین مسیر',
  'Packet loss': 'افت بسته',
  'Start session': 'شروع اتصال',
  'Stop session': 'قطع اتصال',
  'Starting…': 'در حال اتصال…',
  'Direct · one node': 'مستقیم · یک گره',
  'Relay · adaptive duplication': 'رله · ارسال تطبیقی چندمسیره',
  'Choose a tunnelling node': 'یک گره تونل انتخاب کنید',
  'Add a VPN route': 'یک مسیر VPN اضافه کنید',
  'Choose traffic mode': 'حالت ترافیک را انتخاب کنید',
  'All IPv4 system traffic': 'تمام ترافیک IPv4 سیستم',
  'Configure a relay': 'رله را تنظیم کنید',
  'No relay selected': 'رله‌ای انتخاب نشده است',
  Configure: 'تنظیم',
  'Set up': 'راه‌اندازی',
  'Game server': 'سرور بازی',
  Relay: 'رله',
  'Your game': 'بازی شما',
  'Path overview': 'نمای مسیر',
  'Setup checklist': 'فهرست راه‌اندازی',
  'Manage routes': 'مدیریت مسیرها',
  'Live telemetry': 'پایش زنده',
  'Network journey': 'مسیر شبکه',
  'Journey breakdown': 'جزئیات مسیر',
  'Route latency history': 'تاریخچه تأخیر مسیر',
  Latency: 'تأخیر',
  Jitter: 'نوسان تأخیر',
  'Probe loss': 'افت بسته‌های آزمایشی',
  'Last 60 received probe samples · refreshed every 2s': '۶۰ نمونه اخیر · به‌روزرسانی هر ۲ ثانیه',
  'Start a session to measure every enabled WireGuard route.': 'برای سنجش مسیرهای فعال WireGuard اتصال را شروع کنید.',
  'No nodes yet': 'هنوز گره‌ای ندارید',
  'New group': 'گروه جدید',
  'Import .conf': 'وارد کردن .conf',
  'Add nodes': 'افزودن گره',
  'Group these nodes': 'این گره‌ها را گروه‌بندی کنید',
  'Put a fleet under one switch so you can pause all of it at once.':
    'گره‌ها را زیر یک کلید قرار دهید تا همگی را با هم متوقف کنید.',
  'Your VPN secrets stay on this PC': 'اطلاعات محرمانه VPN روی همین رایانه می‌ماند',
  'GamePath only decrypts a configuration or login when the local network service needs it.':
    'GamePath پیکربندی یا اطلاعات ورود را فقط هنگام نیاز سرویس شبکه محلی رمزگشایی می‌کند.',
  'These answer to their own switch': 'این موارد کلید مستقل دارند',
  'Direct mode uses one node, so switching this group on picks a single node.':
    'حالت مستقیم از یک گره استفاده می‌کند؛ روشن کردن این گروه فقط یک گره را انتخاب می‌کند.',
  'Relay fleet': 'رله‌ها',
  'Add your VPS locations and enable one relay at a time.': 'مکان‌های VPS را اضافه کنید و هر بار یک رله را فعال کنید.',
  'More regions are planned': 'مناطق بیشتری در راه است',
  'Relay mode': 'حالت رله',
  'Direct mode': 'حالت مستقیم',
  'Lowest loss': 'کمترین افت',
  'No server needed': 'بدون نیاز به سرور',
  'Needs a VPS running the GamePath relay.': 'به VPS با رله GamePath نیاز دارد.',
  'Needs one tunnelling node. SOCKS5 proxies can only be used with a relay.':
    'به یک گره تونل نیاز دارد. پراکسی SOCKS5 فقط با رله کار می‌کند.',
  'Suits your setup': 'مناسب تنظیمات شما',
  'Switch to relay mode': 'تغییر به حالت رله',
  'Routing scope': 'دامنه مسیریابی',
  'Choose what enters GamePath': 'انتخاب ترافیک ورودی به GamePath',
  'Switch modes at any time before starting a session.': 'پیش از شروع اتصال، هر زمان می‌توانید حالت را تغییر دهید.',
  'Selected targets': 'مقصدهای انتخاب‌شده',
  'Whole system': 'کل سیستم',
  'Resolve names through the tunnel': 'حل نام‌ها از طریق تونل',
  'All-IPv4-traffic mode is active': 'حالت تمام ترافیک IPv4 فعال است',
  'IPv6 is not carried': 'ترافیک IPv6 منتقل نمی‌شود',
  'Split group': 'گروه تفکیکی',
  Target: 'مقصد',
  Type: 'نوع',
  Destination: 'مقصد',
  Group: 'گروه',
  Status: 'وضعیت',
  'This group is ready for targets': 'این گروه آماده افزودن مقصد است',
  'Add an app, folder, hostname, or IP range. You can move targets between groups later.':
    'برنامه، پوشه، نام میزبان یا بازه IP اضافه کنید. بعداً می‌توانید مقصدها را جابه‌جا کنید.',
  'Removing this group keeps its targets in Ungrouped.': 'با حذف گروه، مقصدهای آن در «بدون گروه» می‌مانند.',
  'Open a group to manage its traffic targets.': 'برای مدیریت مقصدهای ترافیک، گروه را باز کنید.',
  Ungrouped: 'بدون گروه',
  'Ungrouped targets': 'مقصدهای بدون گروه',
  'Move these into a group anytime': 'هر زمان می‌توانید آن‌ها را به گروه منتقل کنید',
  'Create another group': 'ساخت گروه دیگر',
  'Bundle targets under one on/off switch': 'مقصدها را زیر یک کلید روشن/خاموش جمع کنید',
  'Create your first split group': 'اولین گروه تفکیکی را بسازید',
  'Keep each game and its related services together, then turn the whole group on or off.':
    'هر بازی و سرویس‌های مرتبط را کنار هم بگذارید و کل گروه را روشن یا خاموش کنید.',
  'Traffic rule': 'قانون ترافیک',
  'Add a split-tunnel target': 'افزودن مقصد تونل تفکیکی',
  'Groups let you pause a whole game or workflow without changing its individual targets.':
    'گروه‌ها امکان توقف یک بازی یا جریان کار را بدون تغییر مقصدهای تکی فراهم می‌کنند.',
  Paused: 'متوقف',
  Enabled: 'فعال',
  Disabled: 'غیرفعال',
  Off: 'خاموش',
  On: 'روشن',
  'Carrying traffic': 'در حال انتقال ترافیک',
  Carrying: 'در حال انتقال',
  'Needs a relay': 'به رله نیاز دارد',
  'Paused by group': 'با گروه متوقف شده',
  Transport: 'انتقال',
  Auth: 'احراز هویت',
  Encryption: 'رمزنگاری',
  Secrets: 'اطلاعات محرمانه',
  Address: 'نشانی',
  Protected: 'محافظت‌شده',
  'Key protected': 'کلید محافظت‌شده',
  Certificate: 'گواهی',
  None: 'هیچ‌کدام',
  'Username and password': 'نام کاربری و رمز عبور',
  'Frames only': 'فقط بسته‌ها',
  'Windows RAS': 'Windows RAS',
  'PSK + username': 'PSK + نام کاربری',
  'UDP associate': 'ارتباط UDP',
  'Traffic over time': 'ترافیک در طول زمان',
  Today: 'امروز',
  'This week': 'این هفته',
  'This year': 'امسال',
  'All time': 'همه زمان‌ها',
  Custom: 'دلخواه',
  'Reset statistics': 'پاک کردن آمار',
  From: 'از',
  To: 'تا',
  'Total carried': 'کل ترافیک منتقل‌شده',
  'Unique tunnelled IP traffic': 'ترافیک IP یکتای منتقل‌شده از تونل',
  Uploaded: 'ارسال‌شده',
  Downloaded: 'دریافت‌شده',
  'From this PC': 'از این رایانه',
  'To this PC': 'به این رایانه',
  Yearly: 'سالانه',
  Monthly: 'ماهانه',
  Weekly: 'هفتگی',
  Daily: 'روزانه',
  'usage in the selected range': 'مصرف در بازه انتخاب‌شده',
  Sent: 'ارسال',
  Received: 'دریافت',
  'No traffic recorded in this range yet.': 'هنوز ترافیکی در این بازه ثبت نشده است.',
  'View exact values': 'نمایش مقادیر دقیق',
  Period: 'دوره',
  'Behind GamePath': 'درباره GamePath',
  'Built by primemb': 'ساخته primemb',
  'A better path to your next game.': 'مسیری بهتر برای بازی بعدی شما.',
  Creator: 'سازنده',
  'GamePath on GitHub': 'GamePath در GitHub',
  'Connect on Discord': 'ارتباط در Discord',
  'Relay routing mode': 'روش مسیریابی رله',
  Smart: 'هوشمند',
  Manual: 'دستی',
  'Best two routes': 'دو مسیر برتر',
  'Every healthy route': 'همه مسیرهای سالم',
  'Start with Windows': 'اجرای هم‌زمان با ویندوز',
  'Open GamePath in the background after signing in.': 'پس از ورود به ویندوز، GamePath را در پس‌زمینه باز کنید.',
  'Local diagnostics': 'عیب‌یابی محلی',
  'Keep route latency and packet-loss history for troubleshooting.':
    'تاریخچه تأخیر مسیر و افت بسته را برای عیب‌یابی نگه دارید.',
  'Windows network capabilities': 'امکانات شبکه ویندوز',
  'Split-tunnel interception': 'رهگیری تونل تفکیکی',
  'GamePath Network Service': 'سرویس شبکه GamePath',
  'Reinstall service': 'نصب دوباره سرویس',
  'Install service': 'نصب سرویس',
  'Installing…': 'در حال نصب…',
  'Refresh status': 'به‌روزرسانی وضعیت',
  'Secure SSH setup': 'راه‌اندازی امن SSH',
  'Keep GamePath open. A first-time Rust build can take several minutes.':
    'GamePath را باز نگه دارید. ساخت اولیه Rust ممکن است چند دقیقه طول بکشد.',
  'SOCKS5 proxy': 'پراکسی SOCKS5',
  'Add a proxy node': 'افزودن گره پراکسی',
  'This proxy can carry GamePath traffic': 'این پراکسی می‌تواند ترافیک GamePath را منتقل کند',
  'This proxy cannot be used yet': 'این پراکسی هنوز قابل استفاده نیست',
  Save: 'ذخیره',
  Cancel: 'لغو',
  Close: 'بستن',
  Delete: 'حذف',
  Remove: 'برداشتن',
  Edit: 'ویرایش',
  Test: 'آزمایش',
  Add: 'افزودن',
  Back: 'بازگشت',
  Next: 'بعدی',
  Continue: 'ادامه',
  Ready: 'آماده',
  Loading: 'در حال بارگذاری',
  'Add node': 'افزودن گره',
  'Adding…': 'در حال افزودن…',
  'All applications inside will match': 'همه برنامه‌های داخل پوشه شامل می‌شوند',
  'All VPN nodes': 'همه گره‌های VPN',
  'Attention needed': 'نیاز به بررسی',
  'Auto-configure VPS': 'تنظیم خودکار VPS',
  'Available in relay mode. Direct mode always uses its one selected node.':
    'این گزینه در حالت رله فعال است. حالت مستقیم همیشه از یک گره انتخاب‌شده استفاده می‌کند.',
  'Awaiting route': 'در انتظار مسیر',
  'Awaiting target': 'در انتظار مقصد',
  'Benchmark RTT': 'زمان رفت‌وبرگشت آزمایش',
  'Bundle related apps, services, and destinations under one switch.':
    'برنامه‌ها، سرویس‌ها و مقصدهای مرتبط را زیر یک کلید جمع کنید.',
  'Carrying your traffic': 'در حال انتقال ترافیک شما',
  'Configure Linux VPS': 'تنظیم VPS لینوکس',
  'Configure VPS': 'تنظیم VPS',
  'Configuring VPS…': 'در حال تنظیم VPS…',
  'Could not copy the username. You can add prime_lifesoul on Discord.':
    'کپی نام کاربری ممکن نشد. می‌توانید prime_lifesoul را در Discord اضافه کنید.',
  'Could not load usage statistics.': 'بارگذاری آمار مصرف ممکن نشد.',
  'Could not reset statistics.': 'پاک کردن آمار ممکن نشد.',
  'Create a split group': 'ساخت گروه تفکیکی',
  'Create group': 'ساخت گروه',
  'Credential already protected — leave blank to keep it':
    'اطلاعات ورود محافظت شده است؛ برای نگه داشتن آن خالی بگذارید',
  'Credential protected': 'اطلاعات ورود محافظت‌شده',
  'Current path': 'مسیر فعلی',
  'Current route chain': 'زنجیره مسیر فعلی',
  'Delete all saved usage statistics? This cannot be undone.': 'همه آمار ذخیره‌شده حذف شود؟ این کار برگشت‌پذیر نیست.',
  'Direct mode sends your traffic through one WireGuard, OpenVPN or L2TP/IPsec node. SOCKS5 proxies need a relay.':
    'حالت مستقیم ترافیک را از یک گره WireGuard، OpenVPN یا L2TP/IPsec می‌فرستد. پراکسی SOCKS5 به رله نیاز دارد.',
  'Discord username copied: prime_lifesoul': 'نام کاربری Discord کپی شد: prime_lifesoul',
  'Each carrying node moves relay traffic through its own VPN or proxy hop. Group nodes to switch a whole set on or off at once.':
    'هر گره فعال ترافیک رله را از VPN یا پراکسی خودش می‌فرستد. برای روشن یا خاموش کردن چند گره با هم، آن‌ها را گروه‌بندی کنید.',
  'Every node you enable carries the same packets to a relay you run. When one hop stumbles, the copy that took the other path still arrives on time.':
    'هر گره فعال بسته‌های یکسان را به رله شما می‌رساند. اگر یک مسیر دچار مشکل شود، نسخه‌ای که از مسیر دیگر رفته همچنان می‌رسد.',
  'Frames are encrypted by GamePath, but the proxy hop itself is not':
    'بسته‌ها را GamePath رمزنگاری می‌کند، اما مسیر پراکسی به‌خودی‌خود رمزنگاری ندارد',
  'GamePath Network Service installed and running.': 'سرویس شبکه GamePath نصب و اجرا شد.',
  'GamePath was removed from the VPS.': 'GamePath از VPS حذف شد.',
  'Give this group a clear, recognizable name.': 'برای گروه نامی روشن و قابل تشخیص بگذارید.',
  'Group off': 'گروه خاموش',
  'Group on': 'گروه روشن',
  'It uses': 'استفاده می‌کند از',
  'Lookups use whatever resolver this PC normally uses. Turn this on if a game or site fails to connect while the tunnel itself is healthy.':
    'جست‌وجوی نام‌ها از DNS معمول این رایانه استفاده می‌کند. اگر تونل سالم است ولی بازی یا سایت وصل نمی‌شود، این گزینه را روشن کنید.',
  'Node quality': 'کیفیت گره',
  'Node, traffic mode and the current path': 'گره، حالت ترافیک و مسیر فعلی',
  'Not configured': 'تنظیم نشده',
  'One node, no duplication': 'یک گره، بدون ارسال چندگانه',
  'Preparing deployment': 'آماده‌سازی نصب',
  'Relay probe RTT': 'زمان رفت‌وبرگشت آزمایش رله',
  'Remove from VPS': 'حذف از VPS',
  'Remove relay from VPS': 'حذف رله از VPS',
  'Removing…': 'در حال حذف…',
  'Rename group': 'تغییر نام گروه',
  'Route quality': 'کیفیت مسیر',
  'Routes, traffic mode, relay and the current path chain': 'مسیرها، حالت ترافیک، رله و زنجیره مسیر فعلی',
  'Save changes': 'ذخیره تغییرات',
  'Saving…': 'در حال ذخیره…',
  'Select the game .exe file': 'فایل .exe بازی را انتخاب کنید',
  'Setup complete': 'راه‌اندازی کامل شد',
  'Setup required': 'راه‌اندازی لازم است',
  'Smart uses the best two healthy routes. Manual duplicates through every healthy enabled route. Changes apply when you next start a session.':
    'حالت هوشمند از دو مسیر سالم برتر استفاده می‌کند. حالت دستی بسته‌ها را از همه مسیرهای سالم و فعال می‌فرستد. تغییرات از اتصال بعدی اعمال می‌شوند.',
  'Something went wrong': 'مشکلی پیش آمد',
  'Stop resolving': 'توقف حل نام‌ها',
  'Target collection': 'مجموعه مقصدها',
  'Test connection': 'آزمایش اتصال',
  'Test UDP': 'آزمایش UDP',
  'Testing…': 'در حال آزمایش…',
  'The pre-shared key and password are protected by Windows secure storage':
    'کلید مشترک و رمز عبور با ذخیره‌سازی امن ویندوز محافظت می‌شوند',
  'The server assigns the address and the cipher when the session starts':
    'سرور هنگام شروع اتصال، نشانی و الگوریتم رمزنگاری را تعیین می‌کند',
  'The start date must be on or before the end date.': 'تاریخ شروع باید پیش از تاریخ پایان یا برابر با آن باشد.',
  'These files need a login': 'این فایل‌ها به اطلاعات ورود نیاز دارند',
  'They use': 'استفاده می‌کنند از',
  'This file needs a login': 'این فایل به اطلاعات ورود نیاز دارد',
  'This removes the GamePath service, firewall tables, configuration, clients, and binary from this server.':
    'با این کار سرویس GamePath، قوانین فایروال، تنظیمات، کلاینت‌ها و فایل اجرایی از این سرور حذف می‌شود.',
  'Traffic enabled': 'ترافیک فعال',
  'Traffic paused': 'ترافیک متوقف',
  'Ungrouped nodes': 'گره‌های بدون گروه',
  'Unknown application': 'برنامه ناشناس',
  'Update VPS': 'به‌روزرسانی VPS',
  'Usage statistics reset.': 'آمار مصرف پاک شد.',
  'Waiting for probes': 'در انتظار آزمایش مسیر',
  'Websites and game servers are looked up at the far end of the tunnel, so a filtered or poisoned local resolver cannot send you to the wrong address. Applies to every app on this PC, not only the ones you select.':
    'نام سایت‌ها و سرورهای بازی در انتهای تونل بررسی می‌شود تا DNS محلی فیلترشده یا دست‌کاری‌شده نشانی اشتباه برنگرداند. این تنظیم برای همه برنامه‌های این رایانه اعمال می‌شود.',
  'Your node': 'گره شما',
  'Your VPN node': 'گره VPN شما',
  'WireGuard, OpenVPN or L2TP/IPsec node': 'گره WireGuard، OpenVPN یا L2TP/IPsec',
  'Add a WireGuard, OpenVPN or L2TP/IPsec node from your VPN provider. Direct mode routes through it, so it is all you need. Secrets are protected with Windows secure storage.':
    'یک گره WireGuard، OpenVPN یا L2TP/IPsec از ارائه‌دهنده VPN خود اضافه کنید. حالت مستقیم از همان عبور می‌کند. اطلاعات محرمانه با ذخیره‌سازی امن ویندوز محافظت می‌شوند.',
  'Add a WireGuard, OpenVPN, L2TP/IPsec or SOCKS5 node. Private keys and passwords are protected with Windows secure storage.':
    'یک گره WireGuard، OpenVPN، L2TP/IPsec یا SOCKS5 اضافه کنید. کلیدهای خصوصی و رمزهای عبور با ذخیره‌سازی امن ویندوز محافظت می‌شوند.',
  'Your selected traffic goes through one WireGuard, OpenVPN or L2TP/IPsec node and out to the game from there. A plain split tunnel, with nothing else to run.':
    'ترافیک انتخاب‌شده از یک گره WireGuard، OpenVPN یا L2TP/IPsec عبور می‌کند و سپس به بازی می‌رسد. یک تونل تفکیکی ساده، بدون سرویس اضافی.',
  'Configure relay endpoint': 'تنظیم نشانی رله',
  'New location': 'مکان جدید',
  'Add relay server': 'افزودن سرور رله',
  'No group': 'بدون گروه',
  'Windows VPN': 'VPN ویندوز',
  'Add an L2TP/IPsec node': 'افزودن گره L2TP/IPsec',
  'The L2TP connection works': 'اتصال L2TP کار می‌کند',
  'Windows could not connect': 'ویندوز نتوانست وصل شود',
  'Route latency appears here as soon as a session is running.': 'با شروع اتصال، تأخیر مسیر اینجا نمایش داده می‌شود.',
  'Handled connections': 'اتصال‌های مدیریت‌شده',
  'Traffic currently routed': 'ترافیکی که اکنون مسیریابی می‌شود',
  Application: 'برنامه',
  Connections: 'اتصال‌ها',
  Protocols: 'پروتکل‌ها',
  Latest: 'آخرین',
  active: 'فعال',
  Protocol: 'پروتکل',
  Connected: 'متصل',
  'The node could not be added': 'افزودن گره ممکن نشد',
  Nodes: 'گره‌ها',
  Applications: 'برنامه‌ها',
  nodes: 'گره‌ها',
  applications: 'برنامه‌ها',
  'Statistics period': 'دوره آمار',
  'Traffic routing mode': 'حالت مسیریابی ترافیک',
  'Copy Discord username prime_lifesoul': 'کپی نام کاربری Discord: prime_lifesoul',
  'Removing the group keeps its nodes; they become ungrouped.':
    'با حذف گروه، گره‌های آن به بخش بدون گروه منتقل می‌شوند.',
  'e.g. Istanbul fleet': 'مثلاً گره‌های استانبول',
  'VPS configuration progress': 'پیشرفت تنظیم VPS',
  'Add a SOCKS5 node': 'افزودن گره SOCKS5',
  'Local proxy': 'پراکسی محلی',
  'Leave blank': 'خالی بگذارید',
  'Close group dialog': 'بستن پنجره گروه',
  'Add split tunnel target': 'افزودن مقصد تونل تفکیکی',
  'Close add target dialog': 'بستن پنجره افزودن مقصد',
  'Configure relay': 'تنظیم رله',
  'Enter the OpenVPN login': 'وارد کردن اطلاعات ورود OpenVPN',
  'The login from your provider': 'نام کاربری ارائه‌دهنده',
  'Stored encrypted and never shown again': 'رمزنگاری و ذخیره می‌شود و دوباره نمایش داده نمی‌شود',
  'Provider L2TP': 'ارائه‌دهنده L2TP',
  Required: 'الزامی',
  'Connection mode': 'حالت اتصال',
  'Latency history for every WireGuard route': 'تاریخچه تأخیر همه مسیرهای WireGuard',
  'Dismiss notification': 'بستن اعلان',
  ready: 'آماده',
  error: 'خطا',
  'not-installed': 'نصب نشده',
  'setup-required': 'نیازمند راه‌اندازی',
  idle: 'بیکار',
  'Native engine ready': 'موتور بومی آماده است',
  'Network service is not installed': 'سرویس شبکه نصب نشده است',
  'Privileged network service ready': 'سرویس شبکه آماده است',
  'Signed Wintun library is ready': 'کتابخانه امضاشده Wintun آماده است',
  'Signed WFP capture runtime is ready': 'سامانه رهگیری امضاشده WFP آماده است',
  'Remove VPS': 'حذف VPS',
}

const dynamic: [RegExp, (...parts: string[]) => string][] = [
  [/^Remove (.+)$/, (name) => `حذف ${name}`],
  [/^Delete (.+)$/, (name) => `حذف ${name}`],
  [/^Rename (.+)$/, (name) => `تغییر نام ${name}`],
  [/^Enable (.+)$/, (name) => `فعال کردن ${name}`],
  [/^Disable (.+)$/, (name) => `غیرفعال کردن ${name}`],
  [/^Group for (.+)$/, (name) => `گروه ${name}`],
  [/^Carry traffic through (.+)$/, (name) => `انتقال ترافیک از ${name}`],
  [/^(.+) connection details$/, (name) => `جزئیات اتصال‌های ${name}`],
  [
    /^(\d+) of (\d+) requirements ready — open Setup below\.$/,
    (ready, total) => `${ready} از ${total} پیش‌نیاز آماده است؛ بخش راه‌اندازی را باز کنید.`,
  ],
  [
    /^(\d+) encrypted paths active through (.+)\.$/,
    (count, relay) => `${count} مسیر رمزنگاری‌شده از طریق ${relay} فعال است.`,
  ],
  [
    /^(\d+) routes will carry game traffic through (.+)\.$/,
    (count, relay) => `${count} مسیر ترافیک بازی را از طریق ${relay} می‌فرستد.`,
  ],
  [/^Selected traffic is going through (.+)\.$/, (node) => `ترافیک انتخاب‌شده از ${node} عبور می‌کند.`],
  [/^(.+) will carry your selected traffic\.$/, (node) => `${node} ترافیک انتخاب‌شده را منتقل می‌کند.`],
  [/^(.+) will carry your traffic$/, (node) => `${node} ترافیک شما را منتقل می‌کند`],
  [
    /^(\d+) routing nodes? added; pick exactly one$/,
    (count) => `${count} گره مسیریابی اضافه شده است؛ فقط یکی را انتخاب کنید`,
  ],
  [
    /^(\d+) nodes? added; the relay is reached only through carrying nodes$/,
    (count) => `${count} گره اضافه شده است؛ دسترسی به رله فقط از گره‌های فعال انجام می‌شود`,
  ],
  [/^(\d+) active split-tunnel targets?$/, (count) => `${count} مقصد فعال تونل تفکیکی`],
  [/^(\d+) of (\d+) nodes? carrying$/, (active, total) => `${active} از ${total} گره در حال انتقال`],
  [/^Paused · (\d+) nodes?$/, (count) => `متوقف · ${count} گره`],
  [/^(\d+) of (\d+) carrying$/, (active, total) => `${active} از ${total} فعال`],
  [/^(\d+) active routes?$/, (count) => `${count} مسیر فعال`],
  [/^(\d+) of (\d+) routes carrying traffic$/, (active, total) => `${active} از ${total} مسیر در حال انتقال ترافیک`],
  [/^(\d+) game packets routed$/, (count) => `${count} بسته بازی مسیریابی شد`],
  [/^(\d+) tracked$/, (count) => `${count} مورد ثبت‌شده`],
  [/^(\d+) files could not be added$/, (count) => `افزودن ${count} فایل ممکن نشد`],
  [/^Add (\d+) nodes$/, (count) => `افزودن ${count} گره`],
  [/^Setup — (\d+) of (\d+) ready$/, (ready, total) => `راه‌اندازی — ${ready} از ${total} آماده`],
  [/^(\d+) active · (\d+) targets$/, (active, total) => `${active} فعال · ${total} مقصد`],
  [
    /^No (.+) usage in this range\.$/,
    (category) => `در این بازه مصرفی برای ${translatePersian(category)} ثبت نشده است.`,
  ],
  [/^(.+) · VPS not configured$/, (country) => `${country} · VPS تنظیم نشده است`],
  [/^Version (.+)$/, (version) => `نسخه ${version}`],
  [/^Client (.+) · Alpha build$/, (version) => `کلاینت ${version} · نسخه آزمایشی`],
  [/^Engine (.+) ready$/, (version) => `موتور ${version} آماده است`],
]

export function translatePersian(value: string) {
  const exact = persian[value]
  if (exact) return exact
  for (const [pattern, render] of dynamic) {
    const match = value.match(pattern)
    if (match) return render(...match.slice(1))
  }
  return value
}
